/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#line 1 "tests.check"
#include "between_two_sets.h"
#define SIZE 5
int a[SIZE] = {2, 4, 8, 16, 64};

START_TEST(findGCD_in_A)
{
#line 6
	ck_assert_int_eq(findGCD_inA(a, SIZE), 64);

}
END_TEST

START_TEST(allOfAIsFactor)
{
#line 9
	ck_assert_int_eq(findGCD_inA(a, SIZE), 64);	
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, findGCD_in_A);
    tcase_add_test(tc1_1, allOfAIsFactor);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
