/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#line 1 "tests.check"
#include "between_two_sets.h"
#define SIZE 5
int a[SIZE] = {1, 2, 4, 8, 16};
int b[SIZE] = {32, 64, 128, 256, 512};

START_TEST(findGCD_in_A)
{
#line 7
	ck_assert_int_eq(findGCD_inA(a, SIZE), 16);

}
END_TEST

START_TEST(allOfAIsFactor)
{
#line 10
	ck_assert_int_eq(findGCD_inA(a, SIZE), 16);	

}
END_TEST

START_TEST(findLCD_in_B)
{
#line 13
	ck_assert_int_eq(findLCD_inB(b, SIZE), 32);

}
END_TEST

START_TEST(is_factor_for_allOf_B)
{
#line 16
	ck_assert_int_eq(findLCD_inB(b, SIZE), 32);
	
}
END_TEST

START_TEST(get_total_number_of_factors)
{
#line 19
	ck_assert_int_eq(getBetweens(a, b, SIZE, SIZE), 2);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, findGCD_in_A);
    tcase_add_test(tc1_1, allOfAIsFactor);
    tcase_add_test(tc1_1, findLCD_in_B);
    tcase_add_test(tc1_1, is_factor_for_allOf_B);
    tcase_add_test(tc1_1, get_total_number_of_factors);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
